### ISSUE TITLE
Architecture is not included: i386

### ISSUE THREAD

**Issue by rayidi** [KaOS-Community-Packages/Viber#2]
I'm trying to install it using `rpmbuild -bp viber.spec`.
while running the above I'm getting the following error on my CentOs "2.6.32-504.12.2.el6.i686" server.
error: Architecture is not included: i386

**Comment by demmm** [comment]
KCP is for KaOS, x86_64 support only.
What you need for an i696 Centos server has nothing to do with this package.
Closing
